name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make docker-build

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to ECR
      env:
      run: |
        IMAGE_TAG=latest

        docker tag strava_charts $IMAGE_URI
        docker push $IMAGE_URI:${IMAGE_TAG}

        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Deploy to AWS via sam
      env:
      run: make sam-deploy
        sam deploy \
            --image-repository ${IMAGE_URI} \
            --parameter-overrides EcrImageUri=${IMAGE_URI}:${IMAGE_TAG} \
            --stack-name strava-charts-stack \
            --region ${AWS_REGION} \
            --capabilities CAPABILITY_IAM \
            --template-file build/sam-template.yaml
